apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-a58u
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-a58u
    app.kubernetes.io/part-of: ci10t-786-0008-app
  name: devfile-sample-a58u
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-a58u
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-a58u
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0008-tenant/ci10t-786-0008-app/devfile-sample-a58u@sha256:0aa9db237ae0408dfdb518d50c913aba0a3509daf44358dbe231cdd7fd2b2ee7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
